<?php
/**
 * info.php
 *
 * PHP version 5.2+
 *
 * @author    Philippe Gaultier <pgaultier@sweelix.net>
 * @copyright 2010-2012 Sweelix
 * @license   http://www.sweelix.net/license license
 * @version   1.10.0
 * @link      http://www.sweelix.net
 * @category  views
 * @package   Sweeml.samples.views.shadowboxDemo
 * @since     1.9.0
 */
?><div style="background-color:#ffffff">
	<?php echo Sweeml::link('Close the box manually', Sweeml::raiseCloseShadowboxUrl()) ?>
	<h1>Info generated</h1>

	This is a content generated by the page
</div>